### PR TITLE
use fromFile reader to allow file references in asyncapi specs

### PR DESCRIPTION
**Pull request by vsinger**
Hi!

## Motivation
While checking EventCatalog v2 with my AsyncAPI specs I got a bunch of errors during generation. All of them of type `code: 'invalid-ref'` because referenced files in the AsyncAPI spec could not be found due to relative paths. 
When using `parser.parse()` function it expects all files to be relative to the EventCatalog project folder (as far as I understood it) where I run `npm run generate`. 
This can be solved by using the `fromFile()` function from the `@asyncapi/parser` NPM package which internally sets the relative paths correctly and allows to parse AsyncAPI specs with relative paths.

Let me know if there is anything else to do :)

### CODE REVIEW

**Comment by boyney123** [comment]
Thank you @vsinger , do you have an example AsyncAPI file I can use in this case to add to our tests?

**Comment by vsinger** [comment]
@boyney123 The example of @IsmaelMartinez is one. Thanks for that @IsmaelMartinez. Any file references in the AsyncAPI spec cause this errors. 

But there is still an issue with this PR. The content of the AsyncAPI which is attached to the service is wrong as it contains the relative paths. I need to check how to get the fully parsed AsyncAPI spec without the file references /relative paths.

**Comment by vsinger** [comment]
@boyney123 I couldn't find a better way than use the `document.meta().asyncapi.parsed` value and set convert it to a valid yaml without references with `js-yaml`. I'm not really into JS :D
Let me know if this is ok :)

**Comment by boyney123** [comment]
Hey @vsinger 

I Found a fix #20, let me know if this works for you. I added a test too. Think it requires your external files to be in a format tho. See the tests.

**Comment by boyney123** [comment]
> @boyney123 The example of @IsmaelMartinez is one. Thanks for that @IsmaelMartinez. Any file references in the AsyncAPI spec cause this errors.
> 
> But there is still an issue with this PR. The content of the AsyncAPI which is attached to the service is wrong as it contains the relative paths. I need to check how to get the fully parsed AsyncAPI spec without the file references /relative paths.

Ah yeah makes sense, let me have a look too

**Comment by boyney123** [comment]
Thank you for raising these @vsinger , I have fixed this in #22.

Going to update the AsyncAPI example with how this all works, and the docs too! Will ping back when done.

**Comment by vsinger** [comment]
@boyney123 thanks for the quick response. There is a debug `console.log` statement which logs the whole parsed AsyncAPI spec. Will lead to lots of logs but the fix looks good.

**Comment by boyney123** [comment]
Haha, o dear! Thanks! Glad fix is looking good! Let me know if you need any more help, or if you ever wanna sync for 30min be curious what you are up too and how Catalog can help!

**Pull request closed without merging**
