### PR TITLE
fix(plugin): throw explicit error message on service id not provided

### PR DESCRIPTION
**Pull request by XaaXaaX**
Motivation
The fix resolve the technical exception while the consumers forget to add the mandatory service id while upgrading to version 2.0.0

### CODE REVIEW

**Comment by boyney123** [comment]
Wonder if Zod can help here at all? Any thoughts?

**Comment by XaaXaaX** [comment]
> Wonder if Zod can help here at all? Any thoughts?

@boyney123  Yes for sure , i can tackle it now or do it as later release 
what do you think?

**Comment by boyney123** [comment]
Yeah be curious to see what it looks like now if you want?

**Comment by XaaXaaX** [comment]
I love this 
Screenshot 2024-10-04 at 21 06 03

**Comment by boyney123** [comment]
Thank you for looking into this @XaaXaaX . I merged #66 I think the ability to add new validation in future through schema stuff you added is fine and good. Thanks for raising and also fixing!

**Pull request closed without merging**
